import React from 'react';
import { Typography, Paper, TextField } from '@material-ui/core';

const ClimateStep = ({
  energyBalance,
  emissionReduction,
  onBalanceChange,
  onEmissionChange,
  classes
}) => (
  <>
    <Paper className={classes.paper} elevation={1}>
      <Typography variant="h6" component="h3">
        “Net Energy balance respect to the previous system” or “Amount of energy
        recovered”
      </Typography>
      <div className={classes.climateBody}>
        <Typography component="p" className={classes.climateDescription}>
          Energy (KWh) used in the old process per unit of product divided by
          energy used in the new process for the same unit of product
        </Typography>
        <TextField onChange={onBalanceChange} value={energyBalance} />
      </div>
    </Paper>
    <Paper className={classes.paper} elevation={1}>
      <Typography variant="h6" component="h3">
        Reduction of emissions
      </Typography>
      <div className={classes.climateBody}>
        <Typography component="p" className={classes.climateDescription}>
          Emissions of CO2 generated by the old process per unit of
          productdivided by emissions used in the new process for the same unit
          of product
        </Typography>
        <TextField onChange={onEmissionChange} value={emissionReduction} />
      </div>
    </Paper>
  </>
);

export default ClimateStep;
