import React from 'react';
import { connect } from 'react-redux';
import { withStyles } from '@material-ui/core/styles';
import { Typography, Paper, TextField } from '@material-ui/core';
import { setEnergyBalance, setEmissionReduction } from '../actions';

const styles = () => ({
  paper: {
    marginTop: '10px',
    width: '40%',
    padding: '10px',
    boxSizing: 'border-box',
    margin: 'auto'
  },
  climateDescription: {
    textAlign: 'left'
  },
  climateBody: {
    display: 'flex',
    justifyContent: 'space-between'
  }
});

const ClimateStep = ({ onBalanceChange, onEmissionChange, classes }) => {
  return (
    <>
      <Paper className={classes.paper} elevation={1}>
        <Typography variant="h6" component="h3">
          “Net Energy balance respect to the previous system” or “Amount of
          energy recovered”
        </Typography>
        <div className={classes.climateBody}>
          <Typography component="p" className={classes.climateDescription}>
            Energy (KWh) used in the old process per unit of product divided by
            energy used in the new process for the same unit of product
          </Typography>
          <TextField onChange={onBalanceChange} />
        </div>
      </Paper>
      <Paper className={classes.paper} elevation={1}>
        <Typography variant="h6" component="h3">
          Reduction of emissions
        </Typography>
        <div className={classes.climateBody}>
          <Typography component="p" className={classes.climateDescription}>
            Emissions of CO2 generated by the old process per unit of
            productdivided by emissions used in the new process for the same
            unit of product
          </Typography>
          <TextField onChange={onEmissionChange} />
        </div>
      </Paper>
    </>
  );
};

const mapDispatchToProps = dispatch => ({
  onBalanceChange: event => dispatch(setEnergyBalance(event.target.value)),
  onEmissionChange: event => dispatch(setEmissionReduction(event.target.value))
});

export default withStyles(styles)(
  connect(
    null,
    mapDispatchToProps
  )(ClimateStep)
);
